[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
mantle = "https://rpc.mantle.xyz"
mantle_testnet = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle = { key = "" }
mantle_testnet = { key = "" }
